import sys
import json
import requests
import datetime

def generate_itinerary(destination, vibes, free_time):
    # Detect available model
    try:
        models_resp = requests.get('http://127.0.0.1:11434/api/tags')
        if models_resp.status_code == 200:
            models = models_resp.json().get('models', [])
            if models:
                model_name = models[0]['name']  # Use the first available model
            else:
                return json.dumps({"error": "No models found in Ollama"})
        else:
            return json.dumps({"error": "Could not connect to Ollama"})
    except requests.exceptions.ConnectionError:
        return json.dumps({"error": "Ollama service not running"})

    # Prepare prompt
    final_prompt = f"""
    You are a professional travel expert.
    User wants a trip to: "{destination}"
    Vibe: "{vibes}"
    Time: "{free_time}"
    
    Task:
    1.  Act as a LOCAL GUIDE specifically for **{destination}**.
    2.  Check if {destination} is a known city/region. If it is in Bangladesh, DO NOT generalize to "Bangladesh". Focus ONLY on {destination}.
    3.  Analyze weather for {destination} in {free_time}.
    4.  Create a 3-day itinerary that contains REAL, SPECIFIC spots in {destination}.
        *   Example: If destination is "Bandarban", mention "Nilagiri", "Nafakhum", "Golden Temple". Do NOT mention "Cox's Bazar" or "Sylhet".
    5.  Local Tip: Must be specific to {destination}.
    
    IMPORTANT: The "destination" field in JSON must be exactly "{destination}".
    
    Output structured JSON ONLY:
    {{
        "destination": "{destination}",
        "weather_summary": "Specific weather for {destination} in {free_time}",
        "itinerary": [
            {{"day": 1, "plan": "Specific places in {destination} to visit in morning, afternoon, evening."}},
            {{"day": 2, "plan": "More specific spots in {destination}."}},
            {{"day": 3, "plan": "Hidden gems in {destination}."}}
        ],
        "packing_list": ["item1", "item2"],
        "local_tip": "Unique tip for {destination}",
        "vibe_match_score": 100
    }}
    """

    try:
        response = requests.post('http://127.0.0.1:11434/api/generate', json={
            "model": model_name,
            "prompt": final_prompt,
            "format": "json",
            "stream": False
        })
        
        if response.status_code == 200:
            result = response.json()
            return result['response'] # Returns the JSON string content generated by model
        else:
            return json.dumps({"error": f"Ollama API Error: {response.text}"})

    except Exception as e:
        return json.dumps({"error": str(e)})

if __name__ == "__main__":
    try:
        # Read args from stdin or command line
        if len(sys.argv) > 1:
            input_data = json.loads(sys.argv[1])
            destination = input_data.get('destination', 'Bangladesh')
            vibes = input_data.get('vibes', 'Relaxed')
            free_time = input_data.get('free_time', 'Anytime')
            
            result = generate_itinerary(destination, vibes, free_time)
            print(result)
        else:
            print(json.dumps({"error": "No input provided"}))
    except Exception as e:
        print(json.dumps({"error": f"Script Error: {str(e)}"}))
