import sys
import json
import requests
import datetime

# Mock Weather Data (Local-first "own data")
WEATHER_DATA = {
    "Sylhet": {
        "summer": "Hot and humid with heavy rainfall (Monsoon)",
        "winter": "Mild and pleasant, perfect for tea gardens",
        "spring": "Warm with occasional showers",
        "autumn": "Cool and comfortable"
    },
    "Sitakunda": {
        "summer": "Hot and humid, good for waterfalls but slippery trails",
        "winter": "Cool and dry, ideal for trekking Chandranath Hill",
        "spring": "Pleasant coastal breeze",
        "autumn": "Moderate temperatures"
    }
}

def get_weather_context(month):
    season = "summer"
    if month in [11, 12, 1, 2]:
        season = "winter"
    elif month in [3, 4]:
        season = "spring"
    elif month in [9, 10]:
        season = "autumn"
    
    return {
        "Sylhet": WEATHER_DATA["Sylhet"][season],
        "Sitakunda": WEATHER_DATA["Sitakunda"][season]
    }

def generate_itinerary(vibes, free_time):
    # Parse free_time to get month (simple logic)
    # Assuming free_time is a string like "July 2024" or "Next weekend"
    # For simplicity, default to current month if not parsable or just ask Ollama to infer
    current_month = datetime.datetime.now().month
    weather_context = get_weather_context(current_month)

    # Detect available model
    try:
        models_resp = requests.get('http://127.0.0.1:11434/api/tags')
        if models_resp.status_code == 200:
            models = models_resp.json().get('models', [])
            if models:
                model_name = models[0]['name']  # Use the first available model
            else:
                return json.dumps({"error": "No models found in Ollama"})
        else:
            return json.dumps({"error": "Could not connect to Ollama"})
    except requests.exceptions.ConnectionError:
        return json.dumps({"error": "Ollama service not running"})

    # Prepare prompt
    final_prompt = f"""
    You are a travel expert for Bangladesh. Create a JSON ONLY response for a trip to Sylhet or Sitakunda.
    User vibe: "{vibes}"
    Free time: "{free_time}"
    
    Weather context:
    Sylhet: {weather_context['Sylhet']}
    Sitakunda: {weather_context['Sitakunda']}
    
    Output structured JSON:
    {{
        "destination": "Name",
        "weather_summary": "Short description",
        "itinerary": [
            {{"day": 1, "plan": "detailed plan"}},
            {{"day": 2, "plan": "detailed plan"}},
            {{"day": 3, "plan": "detailed plan"}}
        ],
        "packing_list": ["item1", "item2"],
        "vibe_match_score": 85
    }}
    """

    try:
        response = requests.post('http://127.0.0.1:11434/api/generate', json={
            "model": model_name,
            "prompt": final_prompt,
            "format": "json",
            "stream": False
        })
        
        if response.status_code == 200:
            result = response.json()
            return result['response'] # Returns the JSON string content generated by model
        else:
            return json.dumps({"error": f"Ollama API Error: {response.text}"})

    except Exception as e:
        return json.dumps({"error": str(e)})

if __name__ == "__main__":
    try:
        # Read args from stdin or command line
        if len(sys.argv) > 1:
            input_data = json.loads(sys.argv[1])
            vibes = input_data.get('vibes', 'Relaxed')
            free_time = input_data.get('free_time', 'Anytime')
            
            result = generate_itinerary(vibes, free_time)
            print(result)
        else:
            print(json.dumps({"error": "No input provided"}))
    except Exception as e:
        print(json.dumps({"error": f"Script Error: {str(e)}"}))
